---
global:
  pattern: event-driven-ansible-starter-kit
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
main:
  clusterGroupName: prod
  multiSourceConfig:
    enabled: true
    clusterGroupGitRepoUrl: https://github.com/mhjacks/clustergroup-chart
    clusterGroupChartGitRevision: add_rbac
